name: Sonar Cloud Code Analysis

on: 
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}

jobs:
  analyze_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Analyse code with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=darraghc-key
            -Dsonar.projectKey=DarraghC_DC_bmi_calculator
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.verbose=true
        