name: Sonar Cloud Code Analysis

on: 
  push:

jobs:
  analyze_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Analyse code with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=DarraghC
            -Dsonar.projectKey=darraghc
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}